platform :ios, '9.0'

target 'PasswordManager' do
pod ‘FMDB’
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PasswordManager

end
